name: esd_ind
channels:
  - defaults
dependencies:
  - importlib-metadata=8.7.0=pyhe01879c_1
  - python_abi=3.10=2_cp310
  - platformdirs=4.4.0=pyhcf101f3_0
  - tk=8.6.15=h54e0aa7_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - libffi=3.4.4=h6a678d5_1
  - libstdcxx=15.2.0=h8f9b012_6
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - sqlite=3.50.2=hb25bd0a_1
  - zeromq=4.3.5=h387f397_9
  - pyzmq=27.1.0=py310h4f33d48_0
  - openssl=3.5.4=h26f9b46_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - readline=8.3=hc2a1206_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pthread-stubs=0.3=h0ce48e5_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - psutil=7.1.0=py310h7c4b9e2_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - libsodium=1.0.20=h4ab18f5_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - ipykernel=6.30.1=pyh82676e8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - libzlib=1.3.1=hb25bd0a_0
  - libgcc-ng=15.2.0=h69a702a_6
  - lmdb=0.9.31=hd590300_1
  - _openmp_mutex=5.1=1_gnu
  - krb5=1.21.3=h723845a_4
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.5=h7934f7d_0
  - executing=2.2.1=pyhd8ed1ab_0
  - _libgcc_mutex=0.1=main
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - python=3.10.18=h1a3bd86_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - parso=0.8.5=pyhcf101f3_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - debugpy=1.8.17=py310h25320af_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - setuptools=78.1.1=py310h06a4308_0
  - tornado=6.5.2=py310h7c4b9e2_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xz=5.6.4=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libgomp=15.2.0=h767d61c_6
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - libkrb5=1.21.3=h520c7b4_4
  - pygments=2.19.2=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - stack_data=0.6.3=pyhd8ed1ab_1
  - ca-certificates=2025.12.2
  - zipp=3.23.0=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - libgcc=15.2.0=h767d61c_6
  - zlib=1.3.1=hb25bd0a_0
  - pip
  - ipython=8.37.0=pyh8f84b5b_0
  - expat=2.7.1=h6a678d5_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - pandas[version='>=1.2.0']
prefix: /scratch/kinshuk/anaconda3/envs/esd_ind
